/*
 * Generated by erpcgen 1.4.0 on Tue May  2 17:15:40 2017.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_portmapper_server_h_)
#define _erpc_portmapper_server_h_


#ifdef __cplusplus
#include "erpc_portmapper.h"
#include "server.h"
#include <stdint.h>
#include <stdbool.h>


/*!
 * @brief Service subclass for portmapper.
 */
class portmapper_service : public erpc::Service
{
public:
    portmapper_service() : Service(kportmapper_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *transport);

private:
    /*! @brief Server shim for register_service of portmapper interface. */
    erpc_status_t register_service_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for register_entry of portmapper interface. */
    erpc_status_t register_entry_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for unregister_service of portmapper interface. */
    erpc_status_t unregister_service_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for unregister_entry of portmapper interface. */
    erpc_status_t unregister_entry_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for lookup of portmapper interface. */
    erpc_status_t lookup_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for lookup_proto of portmapper interface. */
    erpc_status_t lookup_proto_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);

    /*! @brief Server shim for dump of portmapper interface. */
    erpc_status_t dump_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, erpc::Transport *inner_transport, uint32_t sequence);
};

extern "C" {
#endif

typedef void * erpc_service_t;

erpc_service_t create_portmapper_service(void);
#ifdef __cplusplus
}
#endif

#endif // _erpc_portmapper_server_h_
